sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - sudo npm install -g diff-so-fancy@0.11.4
  - ./configure --exclude AppStore
  - ./run --describe --verbose
  - ./run Tmux --verbose
  - ./run --verbose
  - ./run --verbose

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
