# Travis CI configuration.

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]

# Test on Ubuntu 14.04 Trusty and macOS 10.13.
os:
  - linux
  - osx
sudo: True
dist: trust
osx_image: xcode9.3

# Use a base Python language.
# Note that this does not affect osx. We use brew's python on osx.
language: java

# Do not try and clone submodules. The ./configure script will do that.
git:
  submodules: false

before_install:
  # Install python3.6 on macOS. Note that an outdated brew python package is
  # already installed, so we must use the upgrade command.
  - if [[ "$(uname)" == "Darwin" ]]; then
      brew update && \
      brew upgrade python && \
      brew install bazel;
    else
      sudo add-apt-repository -y ppa:deadsnakes/ppa && \
      sudo apt-get update && \
      sudo apt-get install -y --no-install-recommends \
          ca-certificates curl g++ git libmysqlclient-dev \
          pkg-config python python-dev python3.6 unzip zip zlib1g-dev && \
      curl -L -o /tmp/bazel.sh https://github.com/bazelbuild/bazel/releases/download/0.14.1/bazel-0.14.1-installer-linux-x86_64.sh && \
      sudo bash /tmp/bazel.sh && \
      rm /tmp/bazel.sh && \
      git clone https://github.com/KhronosGroup/OpenCL-Headers.git /tmp/opencl-headers && \
      git -C /tmp/opencl-headers reset --hard e986688daf750633898dfd3994e14a9e618f2aa5 && \
      sudo mv /tmp/opencl-headers/opencl12/CL /usr/include/CL && \
      rm -rf /tmp/opencl-headers && \
      wget http://portablecl.org/downloads/pocl-0.12.tar.gz && \
      tar xzf pocl-0.12.tar.gz && \
      cd pocl-0.12/ && ./configure && make && sudo make install && cd .. && \
      sudo rm -r pocl-0.12;
    fi

script:
  - ./configure --noninteractive
  # - bazel query --local_resources=400,1,1.0 //...
