sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - echo "Operating System: $TRAVIS_OS_NAME"
  - uname -a

script:
  - ./install.sh
  - ./install.sh

notifications:
  email:
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
