sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - ./configure --exclude AppStore
  - ./run --describe --verbose
  - ./run --verbose
  - ./run --verbose

notifications:
  email:
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
