# bazel boiler plate mostly taken from rules_go/.travis.yml. See:
#   https://github.com/bazelbuild/rules_go/blob/master/.travis.yml

# trusty beta image has jdk8, gcc4.8.4
# FIXME(linux): dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

# workaround submodule public key access.
# See: http://stackoverflow.com/a/24600210
git:
  submodules: false

os:
  # FIXME(linux): - linux
  - osx

# FIXME(linux):
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - clang-3.6

before_install:
  - |
    sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    git submodule update --init --recursive
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install bazel
    else
      echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
      sudo apt-get update
      dpkg -s 'bazel' &>/dev/null || sudo apt-get install -y bazel
    fi

script:
  - source .env
  - $CC --version   # c compiler
  - $CXX --version  # c++ compiler
  - |
    bazel \
      test \
        --verbose_failures \
        --sandbox_debug \
        --test_output=errors \
        --test_strategy=standalone \
        --spawn_strategy=standalone \
        --genrule_strategy=standalone \
        --local_resources=400,1,1.0 \
        //learn/ctci:all
