sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - ./dotfiles.py --debug

notifications:
  email:
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
