sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm
  - test -f /usr/bin/npm && echo "exists" || echo "not exist"
  - test -f /usr/bin/nodejs && echo "exists" || echo "not exist"
  - ls /usr/bin
  - ./configure --exclude AppStore
  - ./run --describe --verbose
  - ./run Tmux --verbose
  - ./run --verbose
  - ./run

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
