os:
  - linux

language: python

python:
  - "3.6"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      which python || brew install python && brew link --overwrite python
      python --version
    fi
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo apt-get update -qq
      sudo apt-get install -y pocl
    fi

install:
  - make install

script:
  - make test
