language: python

python:
  - "2.7"
# FIXME: Only test one version while I figure out the Travis CI conf:
#  - "3.4"
#  - "3.5"

# faster builds plz
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libhdf5-serial-dev

env:
  global:
    - CC=gcc-4.8
    - CXX=g++-4.8

install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy numpy>=1.10.4
  - pip install --only-binary=scipy scipy>=0.16.1
  - pip install --only-binary=pandas pandas>=0.19.0
  - pip install Cython==0.23.4
  - pip install -r requirements.txt
  - python ./setup.py install

script:
  - make native
  - python ./setup.py test

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
