sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - sudo apt-get install -y tmux
  - dpkg -s 'tmux'
  - dpkg -s 'notapackage'
  - ./configure --exclude AppStore,Node
  - ./run --verbose Git
  - ./run --verbose Unzip
  - ./run --verbose Curl
  - ./run --verbose Python
  - ./run --describe --verbose
  - ./run Tmux --verbose
  - ./run --verbose
  - ./run

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
