# build environment
#
# We need the extra RAM that a non-container build gives us.
#
# See: https://docs.travis-ci.com/user/ci-environment/
sudo: required

language: python

python:
  - "2.7"
# FIXME: Only test one version while I figure out the Travis CI conf:
#  - "3.4"
#  - "3.5"

cache:
  directories:
    - native/llvm/3.9.0
    - native/cmake
    - native/ninja

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6
      - libhdf5-serial-dev
      - python-dev

env:
  global:
    - CC=clang
    - CXX=clang++
    - GPU=0

# note that we pipe the install output to /dev/null because it's too verbose
# (thousands of files are copied from clgen/data/libclc).
install:
  - make llvm
  - make native
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy numpy>=1.10.4
  - pip install --only-binary=scipy scipy>=0.16.1
  - pip install --only-binary=pandas pandas>=0.19.0
  - pip install Cython==0.23.4
  - pip install -r requirements.txt
  - python ./setup.py install >/dev/null

script:
  - python ./setup.py test

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
