sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - ./configure --exclude AppStore
  - ./run --verbose Node
  - ./run --describe --verbose
  - ./run Tmux --verbose
  - ./run --verbose
  - ./run

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
