# Travis CI configuration.

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]

# Test on Ubuntu 14.04 Trusty and macOS 10.13.
os:
  - linux
  - osx
sudo: False
dist: trust
osx_image: xcode9.3

# Use a base Python language.
# Note that this does not affect osx. We use brew's python on osx.
language: java

# Do not try and clone submodules. The ./configure script will do that.
git:
  submodules: false

# TODO(cec): Use LD_PRELOAD if necessary, else remove this.
# Fix for TensorFlow malloc.
# See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156
# LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

before_install:
  # Install python3.6 on macOS. Note that an outdated brew python package is
  # already installed, so we must use the upgrade command.
  - if [[ "$(uname)" == "Darwin" ]]; then brew update && brew upgrade python; fi
  # Fix for TensorFlow malloc.
  # See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156
  - if [[ "$(uname)" != "Darwin" ]]; then sudo apt-get update && sudo apt-get install libtcmalloc-minimal4; fi

script:
  - ./configure --noninteractive
  # - bazel query --local_resources=400,1,1.0 //...
