# We need the extra RAM that a non-container build gives us.
# See: https://docs.travis-ci.com/user/ci-environment/
# trusty beta image has jdk8, gcc4.8.4
# FIXME(linux): dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8

python:
  - "3.6"

# Defer checkout of submodules until ./configure script.
git:
  submodules: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      # Fix for TensorFlow malloc.
      # See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156
      - libtcmalloc-minimal4 

env:
  global:
    # Fix for TensorFlow malloc.
    # See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156
    - LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

before_install:
  - if [[ "$(uname)" == "Darwin" ]]; then brew upgrade && brew install python; fi

script:
  - ./configure --noninteractive
  # - |
  #   bazel test --local_resources=400,1,1.0 \
  #       $(bazel query //... | grep -v -f .travisignore)

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
