language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install numpy scipy scikit-learn pandas coveralls matplotlib
  # Coverage packages are on a binstar channel:
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python ./setup.py install

script:
  - coverage run --source=labm8 ./setup.py test

after_success:
  # Create coverage report:
  - coveralls

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
