# build environment
#
# We need the extra RAM that a non-container build gives us.
#
# See: https://docs.travis-ci.com/user/ci-environment/
sudo: required

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
    - native/cmake
    - native/libclc
    - native/llvm/3.9.0
    - native/ninja
    - native/torch/trunk/build

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6
      - libhdf5-serial-dev
      - python-dev

env:
  global:
    - CC=clang
    - CXX=clang++

before_install:
  # note we can't build openblas with the Travis clang toolchain:
  - sed '/install_openblas /d' -i native/torch/trunk/src/install-deps
  #
  - pip install --upgrade pip
  - pip install coveralls
  - pip install --only-binary=numpy numpy>=1.10.4
  - pip install --only-binary=scipy scipy>=0.16.1
  - pip install --only-binary=pandas pandas>=0.19.0
  - pip install Cython==0.23.4

# A clean Travis CI build will timoeut after 50 minutes and fail. Irritatingly,
# this means that the caches are not updated, so we can't incrementally build
# the project by restarting the job. Instead, split the build into smaller
# jobs:
#
# install:  # part 1
#   - make $TRAVIS_BUILD_DIR/native/llvm/3.9.0/src/include/llvm/CMakeLists.txt
#   - make cmake
#   - make ninja
#   - mkdir -p native/llvm/3.9.0/build
#   - cd $TRAVIS_BUILD_DIR/native/llvm/3.9.0/build && $TRAVIS_BUILD_DIR/native/cmake/3.5.0/bin/cmake $TRAVIS_BUILD_DIR/native/llvm/3.9.0/src -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=true -DLLVM_TARGETS_TO_BUILD=X86 -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DCLANG_ENABLE_ARCMT=OFF -DCMAKE_MAKE_PROGRAM=$TRAVIS_BUILD_DIR/native/ninja/1.7.1/ninja -G Ninja -Wno-dev
#
install:  # part 2 (restart job until LLVM is compiled)
  - mkdir -p native/llvm/3.9.0/build
  - cd $TRAVIS_BUILD_DIR/native/llvm/3.9.0/build && (timeout 1200 $TRAVIS_BUILD_DIR/native/ninja/1.7.1/ninja || true)
#
# install:  # part 3
#   - ./configure -b
#   - make llvm
#   - make native
#
# install:  # part 4
#   - ./configure -b
#   - make llvm
#   - make native
#
# install:  # cache hot
#   - ./configure -b
#   - make llvm
#   - make native
#   - pip install -r requirements.txt
#   - python ./setup.py install

script:
  - true
  # - coverage run --source=clgen ./setup.py test

# after_success:
#   - coveralls

notifications:
  email:
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
