# We need the extra RAM that a non-container build gives us.
# See: https://docs.travis-ci.com/user/ci-environment/
# trusty beta image has jdk8, gcc4.8.4
# FIXME(linux): dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8

python:
  - "3.6"

# workaround submodule public key access.
# See: http://stackoverflow.com/a/24600210
git:
  submodules: false

os:
  - linux
  - osx

# Install some of the requirements that the former CLgen install-deps.sh
# script did.
# See: https://github.com/ChrisCummins/phd/blob/2c35bb1ff45665605ebf4ca7b243d3cb277212aa/deeplearning/clgen/install-deps.sh
addons:
  apt:
    packages:
      - libtcmalloc-minimal4  # fix for TensorFlow malloc. See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156


env:
  global:
    - CC=clang
    - CXX=clang++
    - LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"  # fix for TensorFlow malloc. See: https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-279060156

script:
  - ./configure --noninteractive
  # - |
  #   bazel test --local_resources=400,1,1.0 \
  #       $(bazel query //... | grep -v -f .travisignore)

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]
